services:
  db:
    image: postgres
    ports: 
      - 127.0.0.1:5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mariadb
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example