services:
  map:
    build: .
    ports:
      - 3000:3000
    restart: always
    volumes:
      - "${DATADIR:-./data/}mapserver/:/app/data/"
    depends_on:
      - db
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
  db:
    image: postgres
    restart: always
    volumes:
      - ${DATADIR:-./data/}/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres